# Generated by Django 5.0.7 on 2024-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('urlToImage', models.URLField(blank=True, null=True)),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
