# Generated by Django 5.0.7 on 2024-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshistory',
            name='fetched_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newshistory',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
